version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.8
    working_directory: ~/project

jobs:
  ui-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Fix Nightwatch permissions
          command: chmod +x ./node_modules/.bin/nightwatch
      - run:
          name: Run UI tests
          command: npm run test:UI

  api-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run API tests
          command: npm run test:API:win

workflows:
  version: 2
  test_pipeline:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests
