.version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.8  # choose Node version close to yours
    working_directory: ~/project

jobs:
  ui-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run UI tests (Nightwatch)
          command: npm run test:UI
      - store_artifacts: # optional, save reports
          path: reports/ui

  api-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run API tests (Supertest + mock-auth)
          command: npm run test:API:win
      - store_artifacts:
          path: reports/api

workflows:
  test_pipeline:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests
