version: 2.1

orbs:
  browsers: circleci/browser-tools@1.4.8

executors:
  node-browsers:
    docker:
      - image: cimg/node:18.14.0-browsers
  node-basic:
    docker:
      - image: cimg/node:18.14.0

jobs:
  deps-setup:
    executor: node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install project dependencies
          command: npm ci
      - save_cache:
          paths:
            - ./node_modules
          key: npm-cache-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  ui-tests:
    executor: node-browsers
    steps:
      - attach_workspace:
          at: .
      - browsers/install-chrome
      - browsers/install-chromedriver
      - run:
          name: Verify Chrome setup
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Execute Nightwatch tests
          command: npm run test:UI

  api-tests:
    executor: node-basic
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute API test suite
          command: npm run test:API:unix
      - store_artifacts:
          path: api_server.log
          destination: logs/api

workflows:
  version: 2
  pipeline:
    jobs:
      - deps-setup:
          filters:
            branches:
              only: main
      - ui-tests:
          requires:
            - deps-setup
          filters:
            branches:
              only: main
      - api-tests:
          requires:
            - deps-setup
          filters:
            branches:
              only: main
